### ISSUE TITLE
Muted role

### ISSUE THREAD

**Issue by MilkyyBear** [aternosorg/modbot#161]
Muted role command won’t work for me and it gives me errors, what do I do? I’m probably doing it wrong so I need assistance. I tried !mutedrole create [id] but it didn’t work. !mutedrole enable isn’t a command. !mutedrole disable is though. Please help me.

**Comment by BluewyDev** [comment]
Have you tried doing `!mutedrole <role ID or mention>`?

**Comment by JulianVennen** [comment]
`!mutedrole create` or `!mutedrole <roleid|mention>`
Make sure the bot has the manage roles and manahe channels permission

**Comment by MilkyyBear** [comment]
> `!mutedrole create` or `!mutedrole <roleid|mention>`
> Make sure the bot has the manage roles and manage channels permission

I gave it admin but it just gives me errors when I type !mutedrole @Muted or !mutedrole create

**Comment by BluewyDev** [comment]
What errors exactly?

**Comment by MilkyyBear** [comment]
![image](https://user-images.githubusercontent.com/72638787/103159596-2fa76500-4799-11eb-8e0f-5320c039caaa.png)

**Comment by JulianVennen** [comment]
this should be fixed now ^^

**Comment by MilkyyBear** [comment]
Thanks! It works now.
