### ISSUE TITLE
badwords filter

### ISSUE THREAD

**Issue by StoneMcYT** [aternosorg/modbot#179]
it aint working im not very sure why but im pretty sure its my fault also im not self hosting
![image](https://user-images.githubusercontent.com/67421882/106279631-adb6ca00-6277-11eb-8f65-5e5c8ef772ce.png)

**Comment by BluewyDev** [comment]
You need to specify either regex, include or match

You can't do that as a full command

Example:
![Screenshot_20210129_142437_com discord](https://user-images.githubusercontent.com/34064010/106280136-c99d7a00-623d-11eb-978d-2c8100108d04.jpg)

**Comment by StoneMcYT** [comment]
also whats the difference between those 3?

**Comment by BluewyDev** [comment]
Match will delete any messages with the bad word
Include will only delete Messages that have the bad word in it alone

Regex basically is a sequence of characters

**Comment by BluewyDev** [comment]
I mixed up match and include,
Match only deletes messages that have the bad word alone
Include deletes any message that has the bad word in it

**Comment by StoneMcYT** [comment]
thx alot

**Comment by StoneMcYT** [comment]
Also how do i have multiple punishments

**Comment by BluewyDev** [comment]
!punishment <count> <action> (duration)
Just change strike count and you got another punishment

Changing mute time within punishment would require deleting it and then adding it again

**Comment by JulianVennen** [comment]
`!punishment <count> <action> (duration)`
is what bluewy wanted to type

if you want to set the mute duration of a badword to 5m just enter "mute 5m" as the punishment

**Comment by BluewyDev** [comment]
> `!punishment <count> <action> (duration)`
> is what bluewy wanted to type
> 
> if you want to set the mute duration of a badword to 5m just enter "mute 5m" as the punishment

Yeah i keep forgetting <> for some reason just deletes words..

**Comment by StoneMcYT** [comment]
thx
