### ISSUE TITLE
The hole freeking point

### ISSUE THREAD

**Issue by willywinky** [aternosorg/modbot#191]
look, ive been looking for a discord bot that works with aternos for a few weeks and they all miss the point. i would love a discord bot that starts or ends your server thats it. With a sign up or someting like that thx

**Comment by BluewyDev** [comment]
That's not possible as aternos has no API.
Next to that, please don't make issues that aren't directly related to modbot.

**Comment by JulianVennen** [comment]
That has nothing to do with modbot

**Comment by willywinky** [comment]
> That has nothing to do with modbot

i know but i would be a really  good feature
