### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by StoneMcYT** [aternosorg/modbot#197]
![image](https://user-images.githubusercontent.com/67421882/108067250-7c256780-709b-11eb-95c5-962d1eb127e6.png)

I have legitmanly no idea what this is

**Comment by JulianVennen** [comment]
The "mysql" package we use to connect to the database doesnt support mysql 8's default authentication method.
You probably need to run `ALTER USER '{user}'@'{address}' IDENTIFIED WITH mysql_native_password '{password}` and then `FLUSH PRIVILEGES` to change the authentication method.
I will look at chaning to mysql2 which does support the new default

**Comment by StoneMcYT** [comment]
I just installed MySQL what do you mean by adress

**Comment by JulianVennen** [comment]
if you have mysql on the same machine as the bot use 'localhost'
you can also use '%' to allow all addresses

**Comment by StoneMcYT** [comment]
![image](https://user-images.githubusercontent.com/67421882/108068646-513c1300-709d-11eb-83ff-e21d1159be7d.png)
Is this right 
at the end i left my password there

**Comment by StoneMcYT** [comment]
Okay so it seams like tis my fault for not congrating stuff in the first place
![image](https://user-images.githubusercontent.com/67421882/108069319-33bb7900-709e-11eb-8d8a-3ce671475081.png)

i thought it was okay to leave these things blank and not configrating them so thats the issue right?

**Comment by JulianVennen** [comment]
You obviously need to specify the username, password etc. in the config.json.

**Comment by StoneMcYT** [comment]
Yeah just realzied umm how do i even config theses sorry im new to MySQL im using Fedora linux btw

**Comment by StoneMcYT** [comment]
Nvm im just gonna stick to carl-bot

**Comment by JulianVennen** [comment]
You could also invite our publicly hosted version [here](https://discordapp.com/oauth2/authorize?client_id=790967448111153153&scope=bot&permissions=268446806)
