### ISSUE TITLE
deletemoderation command help menu bug

### ISSUE THREAD

**Issue by Salvi0** [aternosorg/modbot#207]
When you use the deletecommad (cmd) without any input the bot will output an error instead of showing the usual hep menu. Using the command help deletemoderation work as intended tho.
[proof](https://ezic.report.sys.salvi0.xyz/media/Discord_skv6NWFYHu.png).

**Comment by JulianVennen** [comment]
Thanks for the bug report I took a look at it and submitted a PR with a fix
