### ISSUE TITLE
Same help menu error on other 2 commands

### ISSUE THREAD

**Issue by Salvi0** [aternosorg/modbot#211]
This time the error appeared on the ping command.
!help ping (ik it's useless since everyone should know what this type of command do). 

And on the logchannel one (this one without input)

!logchannel
[proof](https://user-images.githubusercontent.com/66015217/109399505-7b19f300-7943-11eb-9593-da86851c0cc8.jpg)

**Comment by JulianVennen** [comment]
Once again thanks for the reports ^^
These should be fixed in #212

**Comment by Salvi0** [comment]
You are welcome. I'm always ready to test new things ^^

**Comment by Salvi0** [comment]
Before this issue will be closed, I found another bug. This time is a completely different thing.
When I try to use the purge command, after he deleted the message the bot will output an error
[proof 1](https://user-images.githubusercontent.com/66015217/109403729-94c93380-795f-11eb-8587-154a8ead90cf.jpg)
[proof 2](https://user-images.githubusercontent.com/66015217/109403731-9dba0500-795f-11eb-8601-091ff6dda4f9.jpg)

**Comment by Salvi0** [comment]
A new error i encountered is regarding the automod (spam, similar messages, maxmentions). Upon inviting the bot and viewing the settings panel their value are setted to undefined. This also trigger them immediately. For example if I invite the bot in a new server and a normal user talk he get punished for spamming even if the automod should be disabled upon inviting the bot.
[proof](https://user-images.githubusercontent.com/66015217/109416956-ba872480-79c1-11eb-9ca5-400ee7edea00.jpg)

**Comment by JulianVennen** [comment]
Sorry for taking a bit to get back to this.
I also added these to the PR

**Comment by Salvi0** [comment]
Ok don't worry it's fine ^^

**Comment by JulianVennen** [comment]
should be fixed now ^^
