### ISSUE TITLE
Cant find a file?

### ISSUE THREAD

**Issue by StoneMcYT** [aternosorg/modbot#252]
Well i cant the file that provides the invite command i tried doing a file search but still cant find it

**Comment by StoneMcYT** [comment]
![image](https://user-images.githubusercontent.com/67421882/114559495-5df47600-9c9e-11eb-9bff-03b64ddd4178.png)

**Comment by JulianVennen** [comment]
https://github.com/aternosorg/modbot/blob/master/src/commands/utility/InfoCommand.js
