### ISSUE TITLE
Prefix broken

### ISSUE THREAD

**Issue by StoneMcYT** [aternosorg/modbot#253]
I set my bot to use the prefix m at first and swapped to m! but it still responds to m not m!

**Comment by StoneMcYT** [comment]
So i set my bot prefix as m! in config but it reponds to m

**Comment by JulianVennen** [comment]
I was not able to reproduce this. Did you restart the bot after changing the config?

**Comment by StoneMcYT** [comment]
> I was not able to reproduce this. Did you restart the bot after changing the config?

yes

**Comment by StoneMcYT** [comment]
Im going to try something to restart my host machine first and see if that works

**Comment by StoneMcYT** [comment]
Well that didnt work
![image](https://user-images.githubusercontent.com/67421882/114563521-0ce68100-9ca2-11eb-8f41-c752ee356fd2.png)
![image](https://user-images.githubusercontent.com/67421882/114563555-1839ac80-9ca2-11eb-8dc6-fa1a02e43a79.png)

**Comment by JulianVennen** [comment]
looks like "m" is your guild prefix.
You can change that with m!prefix

**Comment by StoneMcYT** [comment]
> looks like "m" is your guild prefix.
> You can change that with m!prefix

Works Thanks alot
