### ISSUE TITLE
name is not defined. + database ratelimit.

### ISSUE THREAD

**Issue by Salvi0** [aternosorg/modbot#255]
In one of my tests of the new version i found this strange error that dosen't let the bot define the name const when executing moderation commands.
[proof](https://ezic.report.sys.salvi0.xyz/media/Code_diA6IygVpf.png)

**the error dosen't seem to affect the official bot, i just wanted to warn you guys about this**

The above problem was pretty much fixed in #256 but now everytime the commands !delmod (case ID) or the clearmods (user) are used, the bot hit the database ratelimit showing this error. [proof](https://ezic.report.sys.salvi0.xyz/media/Code_EJ5CGjRl0u.png) (i cannot be sure if this error apply on the official bot too since you can view it only from the console).

**Comment by JulianVennen** [comment]
That's not actually a rate limit from the database, it's a discord rate limit. This doesn't cause any real problems. 
The bot is logging the wrong object there, which will be fixed by #259.
