### ISSUE TITLE
Suggestion: Categorize commands

### ISSUE THREAD

**Issue by mrc2rules** [aternosorg/modbot#258]
It would look neat if the commands were categorised in the help menu. It would make finding a command easier

**Comment by BluewyDev** [comment]
Commands automatically add to the help command upon being made, you can't categorize them easily nor is there any use considering that most of the commands are moderation

**Comment by JulianVennen** [comment]
I will consider that when I'm done refactoring the commands. I have already begun categorizing them in seperate folders but I'm not done refactoring the commands.

**Comment by mrc2rules** [comment]
Categories could be like, User Commands (ones which normal users can use), Moderation, Server Configuration, Other

**Comment by JulianVennen** [comment]
Has been added
