### ISSUE TITLE
Suggestion: Add slash commands

### ISSUE THREAD

**Issue by RvBats** [aternosorg/modbot#337]
It would be fine and best to implement slash commands currently or start for discord.js v13. Especially for moderation commands

**Comment by JulianVennen** [comment]
discord.js v13 has not been release yet.

The development package has a lot of breaking changes. Updating to it requires a lot of work and might take a while.
Supporting multiple users / moderation command is also not really possible for slash commands afaik.

**Comment by RvBats** [comment]
> 
> 
> discord.js v13 has not been release yet.
> 
> The development package has a lot of breaking changes. Updating to it requires a lot of work and might take a while.
> Supporting multiple users / moderation command is also not really possible for slash commands afaik.

I'll help with the changes in v13, actually I made them for the old version with legacy commands. I hope that support for slash commands can be added in the future.

**Comment by JulianVennen** [comment]
The v13 branch should be fully working, I will test it more before merging it.
Slash commands are planned but they can probably only target one user at a time and I might need to change the syntax of some commands

**Comment by RvBats** [comment]
I will be testing everything, the issue of sanctioning multiple users I think I would not have many problems.

**Comment by JulianVennen** [comment]
Will be added in #360
