### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by lukeeey** [aternosorg/modbot#404]
Hello!

Would anyone be against rewriting this in TypeScript? I ask as I don't want to make a PR if the aternos team is not familiar with TS. I'm just looking for something to do.

**Comment by FazeHedgehog** [comment]
Anyone can do what they want the code long as it follows the license, this includes rewriting in TypeScript. I however don't think the team will take up a rewrite for ModBot and replace the JavaScript version entirely.

**Comment by Amgelo563** [comment]
Typescript already compiles to Javascript, perhaps you could write some code on TS and make the PR with what it generates?

**Comment by lukeeey** [comment]
> Typescript already compiles to Javascript, perhaps you could write some code on TS and make the PR with what it generates?

That defeats the point of using TypeScript. TS provides type safety at compile time

**Comment by Amgelo563** [comment]
I see your point then, just wanted to give an alternative in case you meant you were more comfortable writing on TS
