### ISSUE TITLE
ratelimit 

### ISSUE THREAD

**Issue by StoneMcYT** [aternosorg/modbot#454]
My bot keeps bumping into the rate limit any clues and says the slash commands were loaded but it does not appear on my server

![image](https://user-images.githubusercontent.com/67421882/147355397-2308c798-e4c1-4664-b128-bc7ac2ddcf78.png)

Also merry christmas eve

**Comment by BluewyWolff** [comment]
You can ignore the ratelimits part.

Did you invite your bot with the application.commands scope?

**Comment by StoneMcYT** [comment]
Ah no wonder it worked i forgot to add the scope bit thanks for your help Bluewy

**Comment by StoneMcYT** [comment]
Well just realizing when testing the bot i am getting this.
![image](https://user-images.githubusercontent.com/67421882/147389829-03f94328-aac9-4ed6-8683-71bc32a148af.png)

**Comment by BluewyWolff** [comment]
Anything in your logs?

**Comment by StoneMcYT** [comment]
> Anything in your logs?

Nope,
![image](https://user-images.githubusercontent.com/67421882/147389884-93587ec1-10bd-4dbd-a295-36ec3962a68a.png)

**Comment by JulianVennen** [comment]
We can't help you with partial copies of our source code,
Modbot doesn't log that exact message during startup and should log multiple other messages.

**Comment by StoneMcYT** [comment]
> We can't help you with partial copies of our source code, Modbot doesn't log that exact message during startup and should log multiple other messages.

I may have been running an older version by accident not 100% sure what went wrong but im cloning the most updated version now

**Comment by StoneMcYT** [comment]
> > We can't help you with partial copies of our source code, Modbot doesn't log that exact message during startup and should log multiple other messages.
> 
> I may have been running an older version by accident not 100% sure what went wrong but im cloning the most updated version now

Yea issues fixed was running an outdated version.
![image](https://user-images.githubusercontent.com/67421882/147390136-2bfda102-5d9a-4699-a7ac-7be005277c07.png)
