### ISSUE TITLE
Strike seems to bring up an error message.

### ISSUE THREAD

**Issue by RealmKebab** [aternosorg/modbot#497]
Whenever I strike a person, I says this but the command successfully runs.
![image](https://user-images.githubusercontent.com/73048123/180589062-c3c84eb5-f621-450d-b7c8-9a1dc6d4ae66.png)

**Comment by JulianVennen** [comment]
Are you sure your log channel exists and mod bot has the required permissions to send messages in it?

**Comment by RealmKebab** [comment]
Somehow, the bot was removed from the logging channel.
![image](https://user-images.githubusercontent.com/73048123/180632026-9df808f2-243d-4c69-9b78-ffbbd00f2768.png)
![image](https://user-images.githubusercontent.com/73048123/180632028-26900011-7ef2-4918-ae34-9e2985fb9834.png)
![image](https://user-images.githubusercontent.com/73048123/180632032-245898ff-02f1-4317-aa98-ff00501589af.png)
Thanks.
