### ISSUE TITLE
Forum channels are not correctly detected as channels

### ISSUE THREAD

**Issue by RealmKebab** [aternosorg/modbot#498]
![image](https://user-images.githubusercontent.com/73048123/181614933-68687d24-2ac8-45d1-8633-41e5b6c4b8c8.png)
Upcoming discord forums is pretty great, but the problem is modbot cannot send messages inside of them. (screen from official exaroton server)

**Comment by RealmKebab** [comment]
Of course, pinging the bot "basically threads" isn't gonna do anything.

**Comment by JulianVennen** [comment]
The autoresponse was not set to activate in that channel.
For some reason, discord.js seems to not cache forum channels as channels, which makes it impossible to add forum channels to autoreponses.
Setting the autoresponse to global works.

This will probably require an update to discord.js v14 to fix.

**Comment by RealmKebab** [comment]
> The autoresponse was not set to activate in that channel. For some reason, discord.js seems to not cache forum channels as channels, which makes it impossible to add forum channels to autoreponses. Setting the autoresponse to global works.
> 
> This will probably require an update to discord.js v14 to fix.

Alright, cool. You can close the channel if you have done the update or so.
