### ISSUE TITLE
Sentinel plugin does not work on Aternos.

### ISSUE THREAD

**Issue by Igggosha** [aternosorg/modbot#502]
When using Citizens plugin and Sentinel plugins to get NPCs that attack other mobs (1.19.2, latest versions of plugins) Sentinel plugin is broken. The same goes for 1.19 and 1.19.1. Latest Paper version.

Citizens2: https://aternos.org/addons/a/artemis-bukkit/citizens (2.0.30)
Sentinel: https://aternos.org/addons/a/spigot/22017 (2.6.5)

**Comment by KylePrograms2by2** [comment]
This isn't support for Citizens Plugin. 
You post modbot's code issues here

**Comment by matthi4s** [comment]
https://support.aternos.org/hc/en-us/articles/360027235811-Contact-support
