### ISSUE TITLE
Global auto-responses throw an error

### ISSUE THREAD

**Issue by Soapy7261** [aternosorg/modbot#507]
When you make an auto-response global, it throws an error
![Screenshot_20221024-193431](https://user-images.githubusercontent.com/81933267/197590220-b6143ef1-f591-4cc3-8216-6a451d8f783b.png)
But not when it's not global, at least from testing

**Comment by Dobby-progam** [comment]
The command uses
/auto-response add h type:Include (ignore case) [default] global:true
Whit global false it gives the form to fill in

**Comment by JulianVennen** [comment]
Thanks for the report, this will be fixed by #508
