### ISSUE TITLE
Voice channels chats don't work with auto deletion

### ISSUE THREAD

**Issue by Soapy7261** [aternosorg/modbot#513]
You can look in the aternos discord server in voice channels text channel and see lots of these
![advertisements](https://user-images.githubusercontent.com/81933267/197821108-eaa482ed-8a98-413b-9ff1-22d3cf2362f7.png)

**Comment by JulianVennen** [comment]
This is for issues with ModBot, not for issues with how ModBot is configured on specific servers

**Comment by Soapy7261** [comment]
Oh, sorry, i thought it was a problem with modbot
