### ISSUE TITLE
Badword Editing Type-Changing Quirk and [object Object]

### ISSUE THREAD

**Issue by ToothyDev** [aternosorg/modbot#543]
When editing a badword's type, the modal / popup that appears will not say "regex" and fill in /regex/flags, but will still show e.g. "Trigger" for when it was a text.
Creating the badword like this:
![image](https://user-images.githubusercontent.com/55001472/204011980-18933fd6-e308-4fa6-bfc4-3ead4f3d00c1.png)

and then editing it while changing the type to e.g. regex, it will still show it like this
![image](https://user-images.githubusercontent.com/55001472/204012099-a4f4dada-83be-4599-b383-a26c56ef37e1.png)

Also, creating a punishment without any punishment selected yields [object Object]
![image](https://user-images.githubusercontent.com/55001472/204012233-b1d4b598-d074-4480-ae1c-e8d7481792df.png)

**Comment by ToothyDev** [comment]
The punishment will also revert back to [object Object] when simply using /bad-word edit without any arguments

**Comment by ToothyDev** [comment]
The title of the text field where it says trigger in my screenshot should then be updated to regex, yes. Basically should look the same as if you created a regex badword from scratch, because on my screenshot it looks like you're creating a normal badword

**Comment by JulianVennen** [comment]
The title of the Text field (1) also doesn't say regex when you create a bad word. It is however displayed in the modal title (2).
![image](https://user-images.githubusercontent.com/45244473/205638374-4289bd84-c101-461b-b1a5-1886dc31b451.png)

I think automatically converting the trigger to the matching regex would be a great idea tho

**Comment by ToothyDev** [comment]
Oh yea my bad then, but an autoconversion would be nice too yes. But the prefilled text should also be changed before currently it isn't last time I tested

**Comment by JulianVennen** [comment]
What do you mean with that?

**Comment by ToothyDev** [comment]
https://gdpr-info.eu/issues/fines-penal
![Uploading Screenshot_20221205_133928_Firefox.png…]()
The gray placeholder

**Comment by JulianVennen** [comment]
That is already changed according to the new type

**Comment by ToothyDev** [comment]
My bad, I probably did something wrong when testing it in the first place
