### ISSUE TITLE
[suggestion] Various suggestions.

### ISSUE THREAD

**Issue by yiyoperez** [aternosorg/modbot#545]
Why this suggestion?
More info like message and user id is really important to report those players if needed.

Specify more info when logging deletes messages and bulk deleted messages, also message delete bulk event doesn't log attachments.

Some examples:

(MessageDeleteBulkEventListener)
![image](https://user-images.githubusercontent.com/27533618/206329038-566704c0-2320-47a9-aa63-e91ccb443ab4.png)

(MessageDeleteEmbed)
![image](https://user-images.githubusercontent.com/27533618/206329250-e7e53020-50b3-4541-a31e-b59689c48699.png)

**Comment by JulianVennen** [comment]
> More info like message and user id is really important to report those players if needed.
Report them to whom? Discord generally doesn't accept message deletions logged by bots as evidence.

> Specify more info when logging deletes messages and bulk deleted messages
Which information exactly would you like to see added?

> also message delete bulk event doesn't log attachments.
Bulk deletes are very complicated, as they can be used to delete hundreds of messages within a very short time frame.
To avoid API spam, ModBot can't just repost these messages individually. Instead, it tries to add as many of them as possible and logs that as a single message. Adding attachments to this *could* be possible.

**Comment by JulianVennen** [comment]
To make sure that ModBot can log as many messages as possible, I really want to keep the metadata for bulk deletes short.
How about this:
```
<user-mention> (<message-id>): <message-content>
```
and for messages with files:
```
<user-mention> (<message-id>) 7 files: <message-content>
```

**Comment by JulianVennen** [comment]
Bulk Delete:
![image](https://user-images.githubusercontent.com/45244473/207117451-15983421-422c-47b0-aa85-5172a831a691.png)

Single Message Delete:
![image](https://user-images.githubusercontent.com/45244473/207117559-f1d06dea-25b1-4569-987f-2bdd026e332e.png)

**Comment by Soapy7261** [comment]
I don't really think its needed to have the user ID when you can just right click and copy ID

**Comment by JulianVennen** [comment]
Where? In the single message delete?
There's no mention to click on.

**Comment by JulianVennen** [comment]
The user id is not in the new bulk delete format I proposed.
The old format didn't have a user mention that you could click on.

**Comment by Soapy7261** [comment]
oh wait im an idiot its the message ID 🤦

**Comment by yiyoperez** [comment]
> To make sure that ModBot can log as many messages as possible, I really want to keep the metadata for bulk deletes short. How about this:
> 
> ```
> <user-mention> (<message-id>): <message-content>
> ```
> 
> and for messages with files:
> 
> ```
> <user-mention> (<message-id>) 7 files: <message-content>
> ```

Yes!
I like this proposed format, user mention in bulk format keeps the message short and clean didn't think of it before.
