### ISSUE TITLE
[Bug] Modbot doesn't have error handling for not actually being in a guild

### ISSUE THREAD

**Issue by Soapy7261** [aternosorg/modbot#551]
This sounds confusing but if you invite modbot without the bot scope, it'll throw errors when viewing stuff like autoresponse list and adding autoresponses and other commands
Example invite: https://discord.com/oauth2/authorize?client_id=790967448111153153&scope=applications.commands&permissions=1099780074518
Obviously unless your trying to screw something up, this won't happen but i thought it'd be something to at least know of

**Comment by MiataBoy** [comment]
Not really something worth fixing or looking into. The invite modbot provides includes the bot scope and should always include the bot scope. Screwed up oauth links is not really our problem if the link in the bot is intact.

**Comment by Soapy7261** [comment]
i forgot why i made this
