### ISSUE TITLE
[Suggestion] A full example.config.json

### ISSUE THREAD

**Issue by Soapy7261** [aternosorg/modbot#560]
*Some people* can't seem to figure out how to make a full config or why some things aren't working, so I'd suggest a example.fullconfig.json (similar to [mine in my repo](https://github.com/Soapy7261/modbot)), and the min config would stay the same, this would make it easier for users who don't wanna type out everything, especially emojis, that's hell if you don't know the tricks to get it done fast

**Comment by KylePrograms2by2** [comment]
By some people... You mean me! 😂

**Comment by Soapy7261** [comment]
Yes.

**Comment by JulianVennen** [comment]
I think putting that information in the documentation file is a much better idea than creating more example files.
I made a PR (#561) about that. This adds examples to individual sections of the documentation, as well as a minimal and full example at the end.
