### ISSUE TITLE
[Bug] Aternos modbot doesn't show video options

### ISSUE THREAD

**Issue by RealmKebab** [aternosorg/modbot#567]
![image](https://user-images.githubusercontent.com/73048123/235231204-6610360a-3ca8-45b3-b393-df265a562c11.png)
I'm just trying to assist an person, tried to (almost said buy) type "geyser" Nothing showed up.

It says loading options failed.

**Comment by Dobby-progam** [comment]
Looks like an issue on discords end

**Comment by KylePrograms2by2** [comment]
> ![image](https://user-images.githubusercontent.com/73048123/235231204-6610360a-3ca8-45b3-b393-df265a562c11.png) I'm just trying to assist an person, tried to (almost said buy) type "geyser" Nothing showed up.
> 
> It says loading options failed.

Are you using a Discord App?

**Comment by JulianVennen** [comment]
This has nothing to do with discord. This is an issue with our google API key.

**Comment by JulianVennen** [comment]
fixed
