### ISSUE TITLE
Repeated messages protection 

### ISSUE THREAD

**Issue by MiataBoy** [aternosorg/modbot#569]
The repeated messages protection attempts to block every new repeated message, but in the process of this spams itself because it replies to every new repeated message, this also eventually causes a delay that modbot just looks like it's spamming in itself.

My suggestion would be to make a sort of check that only sends the message once and doesn't do it again if it's the same user in a set timespan

**Comment by JulianVennen** [comment]
ModBot should time out members for 30 seconds when they hit any kind of automod filter

**Comment by MiataBoy** [comment]
Understood, but i mean that modbot replies to every filtered message before deleting them, which causes modbot to spam. I will try to reproduce what i mean.

**Comment by JulianVennen** [comment]
Given that a user should only be able to send a single "spam" message per 30 seconds, that should not be an issue.

**Comment by MiataBoy** [comment]
I can't seem to reproduce it anymore. Apologies.
