### ISSUE TITLE
Import fails (not a modbot or vortex format)

### ISSUE THREAD

**Issue by MiataBoy** [aternosorg/modbot#572]
Terribly sorry to disturb. Modbot now reports that it's own data is not valid for importing

![Screenshot_2023-05-11-01-05-03-674_com discord](https://github.com/aternosorg/modbot/assets/34064010/c4b33349-34ae-43ff-8020-84c2ce763df9)

**Comment by JulianVennen** [comment]
what's the dataType property in that json file?

**Comment by MiataBoy** [comment]
modbot-1.0.0

**Comment by JulianVennen** [comment]
Seems like this was weird behaviour of the discord mobile app

**Comment by Soapy7261** [comment]
> Terribly sorry to disturb. Modbot now reports that it's own data is not valid for importing
> 
> ![Screenshot_2023-05-11-01-05-03-674_com discord](https://user-images.githubusercontent.com/34064010/237533048-c4b33349-34ae-43ff-8020-84c2ce763df9.jpg)

MIATA!!!!!!

**Comment by MiataBoy** [comment]
🚗

**Comment by Soapy7261** [comment]
MIAT
