### ISSUE TITLE
Importing data does not overwrite guild settings

### ISSUE THREAD

**Issue by MiataBoy** [aternosorg/modbot#573]
Data imports do not overwrite the already saved data for a guild, as you may observe here:
![image](https://github.com/aternosorg/modbot/assets/34064010/405cd061-ea96-4529-8c2d-b7a138c384bf)

That is the old data, while the new data would have been this:
![image](https://github.com/aternosorg/modbot/assets/34064010/2a0c595a-ca64-43d7-8ef0-19a111797526)

**Comment by Soapy7261** [comment]
Very true
