### ISSUE TITLE
Mod link

### ISSUE THREAD

**Issue by cyberlooper** [aternosorg/modbot#576]
**Feature Request**

Jash and I had the same idea, so I thought so would ask.

Would it be possible to make a /Google command for Modbot, which provides a "let me Google that for you" link?

Many thanks for considering.

-Z3US-

**Comment by MiataBoy** [comment]
While  I'm not the developer, but just a contributor; I don't think it's worth making this command. It doesn't really suit the bot, and isn't really a serious command. Besides; I'll repeat this, people don't understand what these links mean usually

**Comment by Soapy7261** [comment]
Same

**Comment by JulianVennen** [comment]
I think Miatas comment explains my general thoughts about this pretty well.
An autoresponse that tells people to use Google, and please try to solve problems themselves might be more useful.
