### ISSUE TITLE
new username system broke some things

### ISSUE THREAD

**Issue by Dobby-progam** [aternosorg/modbot#577]
wit the new username system, user that changed there username have for example Modbot#0 this is for the modlogs and the /user command. 

It is fine but maybe something to consider changing for the near future

**Comment by ToothyDev** [comment]
A #0 discriminator is simply the interim solution Discord went with. Neither discord.js nor py-cord updated to reflect these changes yet, so modbot can't really do anything about it unless discord.js properly supports the new naming system

**Comment by Soapy7261** [comment]
discord.py has recently, but most other forks have not

**Comment by Dobby-progam** [comment]
then I will close this 
if the issue is somewhere else
