### ISSUE TITLE
ModBot (purges) the word provided, but also purges the other unrelated messages

### ISSUE THREAD

**Issue by RealmKebab** [aternosorg/modbot#581]
The word I provided is "cuute" (as it keeps on spamming our console, even when the proxy is down)

https://github.com/aternosorg/modbot/assets/73048123/4d0568f8-686f-4739-9b25-4a723014ea52

**Comment by RealmKebab** [comment]
(the word on the second command i provided which i misspelled "cuute" and instead wrote "cuut" (you can't see it, because i cropped it too much))

**Comment by MiataBoy** [comment]
This is already known:
https://github.com/aternosorg/modbot/pull/580

**Comment by RealmKebab** [comment]
ah alr
