### ISSUE TITLE
Modbot can't prevent (aternos server) links being posted in voice chat channels

### ISSUE THREAD

**Issue by RealmKebab** [aternosorg/modbot#585]
![image](https://github.com/aternosorg/modbot/assets/73048123/1798edba-7db2-4d42-8108-522ddb48a08b)
![image](https://github.com/aternosorg/modbot/assets/73048123/b1f70ef6-5dcb-4cd9-9069-4372cc74ebab)

FYI: This is in voice 0 and 1

**Comment by Soapy7261** [comment]
Seems to be an issue with how aternos is configured, not modbot

**Comment by RealmKebab** [comment]
ah

**Comment by Soapy7261** [comment]
Its the same code

**Comment by RealmKebab** [comment]
> Its the same code, its not special, just different config

i'd rather call it the special edition eitherway, it's not the same bot

**Comment by Soapy7261** [comment]
Fair enough

**Comment by JulianVennen** [comment]
Our bad words are intentionally set up like this.

I don't think "Special Edition" ie the right term here and I'm not sure what your cough there is supposed to mean.
It's just another instance of the same code base.
