### ISSUE TITLE
[Suggestion] Safeguards to /purge with no message limit specified

### ISSUE THREAD

**Issue by Soapy7261** [aternosorg/modbot#590]
I went to run `/purge 2` but since there are multiple options and I didn't click on any and since none are actually required, it ignored my input and defaulted to 100 and deleted a bunch of messages that were semi-important, this behaviour is quite strange, it should at least have the limit argument required or if none is given, ask for confirmation that you do indeed want to delete 100 messages.

**Comment by JulianVennen** [comment]
I don't think this is necessary.
If you only want to delete 2 messages then don't use the purge command.

**Comment by Soapy7261** [comment]
But what about something like 50? or just generally something that just generally would take quite a decent bit of time to delete manually, it defaulting to 100, or really any number doesn't make any sense to me, especially since it does not ask for confirmation.
