### ISSUE TITLE
it wont let me strike

### ISSUE THREAD

**Issue by codester15** [aternosorg/modbot#593]
so it says i am missing some perms to execute this command if this happens consistently please create an issue

**Comment by JulianVennen** [comment]
Please provide a screenshot of the full error message.

**Comment by codester15** [comment]
ok 
![Screenshot 2024-02-28 203534](https://github.com/aternosorg/modbot/assets/151576226/44009dec-a8ae-414f-8207-7e35a3fc44a1)

**Comment by JulianVennen** [comment]
Does modbot have the 'moderate members' permission in your server?

**Comment by codester15** [comment]
he has an admin role so i think so

**Comment by codester15** [comment]
@JulianVennen are you still there?

**Comment by JulianVennen** [comment]
Discord is returning a missing permission error, unfortunately it doesn't have many details on what exactly the missing permission is.

**Comment by codester15** [comment]
OK

**Comment by codester15** [comment]
well thats ok i guess

**Comment by codester15** [comment]
so yeah

**Comment by codester15** [comment]
bye
