### ISSUE TITLE
Strike command doesn't work

### ISSUE THREAD

**Issue by ToothyDev** [aternosorg/modbot#601]
Server ID 715969701771083817
Can't strike anyone, regardless of with reason or without.
![image](https://github.com/aternosorg/modbot/assets/55001472/4d99dc2f-ce0c-4efb-86f7-9e940822c8f2)

**Comment by ToothyDev** [comment]
Correction, no moderation command seems to work, not even changing punishments

**Comment by JulianVennen** [comment]
Should be fixed (hopefully permanently)
