### ISSUE TITLE
It's not possible to remove deleted roles from the protected roles

### ISSUE THREAD

**Issue by ToothyDev** [aternosorg/modbot#606]
So currently, I have a protected role that has been deleted. I didn't save its ID, so I can't enter that into the command to remove a protected role. I also can't grab the ID from the embed of the list command since even in inspect element, it just says @unknown-role. I think unknown roles in the settings should just be deleted if they don't resolve to an actual role as it's otherwise impossible to delete them unless you save their ID, which i think could work

**Comment by ToothyDev** [comment]
Found an old message where I pinged said role and managed to grab its ID, but Discord itself won't take that as an argument since it's not a valid role ID (anymore) so it doesn't even reach modbot

**Comment by JulianVennen** [comment]
Fixed in 3.6.2. Just run `/settings protected-roles list`
