### ISSUE TITLE
ModBot Issue wen starting

### ISSUE THREAD

**Issue by skywalker0707** [aternosorg/modbot#80]
Hello, im pretty new with Node.js and in general with Discord bots, so i tried to learn from ModBot since i really want to make my own bot. I followed all the steps from the intall guide but it still not working... I dont know wy here is the error log. (I also installed Discord.js)

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\alumne\downloads\modbot-master\bot.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by skywalker0707** [comment]
> Hello, im pretty new with Node.js and in general with Discord bots, so i tried to learn from ModBot since i really want to make my own bot. I followed all the steps from the intall guide but it still not working... I dont know wy here is the error log. (I also installed Discord.js)
> 
> internal/modules/cjs/loader.js:969
> throw err;
> ^
> 
> Error: Cannot find module 'C:\Users\alumne\downloads\modbot-master\bot.js'
> �[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)�[39m
> �[90m at Function.Module._load (internal/modules/cjs/loader.js:842:27)�[39m
> �[90m at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)�[39m
> �[90m at internal/main/run_main_module.js:17:47�[39m {
> code: �[32m'MODULE_NOT_FOUND'�[39m,
> requireStack: []
> }

I solved it but i came up with a new error :V

(node:52060) UnhandledPromiseRejectionWarning: undefined
(node:52060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:52060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JulianVennen** [comment]
You probably fixed it by running "npm install".
Make sure your database exists the bot has the correct login credentials.
The mysql module also doesnt support newer authentication so during mysql setup you might need to enable legacy support for mysql 5.x
